ENGLISH:
  help:
    title: Basic server bot commands
    exrates: /comm/ where country is CZK|PLN|HUF|EUR
    summoner: /comm/ where server is usually EUN1
    message: Basic commands were send to you

  commands:
    mod:
      activation: Module /module/ has been activated
      deactivation: Module /module/ has been deactivated
    exchange:
      output: These are prices of Riot Point using /curr/ currency.
      title: Riot point prices
    summoner:
      title: /player/'s profile
      lvl: Level
    rotation:
      title: Champion rotation
      value: Champions in this rotation

CZECH:
  help:
    title: Základní přikazy pro tohoto bota
    exrates: /comm/ kde je county CZK|PLN|HUF|EUR
    summoner: /comm/ kde server nahraďte nejčasteji EUN1
    message: Byly ti zaslány zakladní příkazy
  commands:
    mod:
      activation: Modul /module/ byl aktivován
      deactivation: Modul /module/ byl deaktivován
    exchange:
      output: Toto jsou ceny rp pokud budete platit v /curr/.
      title: Ceny Riot pointů
    summoner:
      title: Profil hráče /player/
      lvl: Úroveň hráče
    rotation:
      title: Rotace šampionů
      value: Rotace obsahuje tyto šampiony

  ranks:
    IRON: Železná
    BRONZE: Bronzová
    SILVER: Stříbrná
    GOLD: Zlatá
    PLATINUM: Platinová
    DIAMOND: Diamantová
    MASTER: Mistrovská
    GRANDMASTER: Velmistrovská
    CHALLENGER: Vyzyvatelská

URLs:
  pokimane:
    0: https://d.newsweek.com/en/full/1571727/pokimane-twitch-deal-exclusive-stream-streaming.jpg?w=1600&h=1600&l=57&t=37&q=88&f=2bb3df1fccb5e50c6d2097c34866fb6d
    1: https://storage.googleapis.com/grunex/d2/articles/main/840x473/91022.jpg
    2: https://www.dailyesports.gg/wp-content/uploads/2020/01/poki-1200x900.jpg
    3: https://i2-prod.dailystar.co.uk/incoming/article21646002.ece/ALTERNATES/s615b/0_pokimanelol_67676396_456424211620320_5593184096346389821_n.jpg
    4: https://i.pinimg.com/originals/f2/ba/a1/f2baa16235a44826beb99f4fb008583e.jpg
    5: https://i.pinimg.com/736x/40/8b/34/408b3484cc6f918aad91d8aef8633926.jpg
    6: https://vignette.wikia.nocookie.net/offlinetvandfriends/images/6/64/Pokimane.jpg/revision/latest?cb=20190829112805
    7: https://scontent-atl3-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/c0.115.1080.1080a/s640x640/93861497_2922796664478783_5311820415612567650_n.jpg?_nc_ht=scontent-atl3-1.cdninstagram.com&_nc_cat=103&_nc_ohc=rMEJZyQb-7UAX9hT_vs&oh=b2c2c9308cbdd626e5b7ab18adce7380&oe=5EC95F3E
    8: https://static-prod.weplay.tv/2019-07-03/62fb2a7d4e8999e877ee48a5229ad212_large_cover.jpeg
    9: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQpwajBQT7bVhSDfrpUl2rvTKhceNNvnYqTNEg8ipao7BSgaKiB&usqp=CAU

CHAMPIONS:
  266: Aatrox
  412: Thresh 
  23: Tryndamere 
  79: Gragas 
  69: Cassiopeia 
  136: Aurelion Sol 
  13: Ryze 
  78: Poppy 
  14: Sion 
  1: Annie 
  202: Jhin 
  43: Karma 
  111: Nautilus 
  240: Kled 
  99: Lux 
  103: Ahri 
  2: Olaf 
  112: Viktor 
  34: Anivia 
  27: Singed 
  86: Garen 
  127: Lissandra 
  57: Maokai 
  25: Morgana 
  28: Evelynn 
  105: Fizz 
  74: Heimerdinger 
  238: Zed 
  68: Rumble 
  82: Mordekaiser 
  37: Sona 
  96: Kog'Maw 
  55: Katarina 
  117: Lulu 
  22: Ashe 
  30: Karthus 
  12: Alistar 
  122: Darius 
  67: Vayne 
  110: Varus 
  77: Udyr 
  89: Leona 
  126: Jayce 
  134: Syndra 
  80: Pantheon 
  92: Riven 
  121: Kha'Zix 
  42: Corki 
  268: Azir 
  51: Caitlyn 
  76: Nidalee 
  85: Kennen 
  3: Galio 
  45: Veigar 
  432: Bard 
  150: Gnar 
  90: Malzahar 
  104: Graves 
  254: Vi 
  10: Kayle 
  39: Irelia 
  64: Lee Sin 
  420: Illaoi 
  60: Elise 
  106: Volibear 
  20: Nunu 
  4: Twisted Fate 
  24: Jax 
  102: Shyvana 
  429: Kalista 
  36: Dr. Mundo 
  427: Ivern 
  131: Diana 
  223: Tahm Kench 
  63: Brand 
  113: Sejuani 
  8: Vladimir 
  154: Zac 
  421: Rek'Sai 
  133: Quinn 
  84: Akali 
  163: Taliyah 
  18: Tristana 
  120: Hecarim 
  15: Sivir 
  236: Lucian 
  107: Rengar 
  19: Warwick 
  54: Malphite 
  157: Yasuo 
  101: Xerath 
  17: Teemo 
  75: Nasus 
  58: Renekton 
  119: Draven 
  35: Shaco 
  50: Swain 
  91: Talon 
  40: Janna 
  115: Ziggs 
  245: Ekko 
  61: Orianna 
  114: Fiora 
  9: Fiddlesticks 
  31: Cho'Gath 
  33: Rammus 
  7: LeBlanc 
  16: Soraka 
  26: Zilean 
  56: Nocturne 
  222: Jinx 
  83: Yorick 
  6: Urgot 
  203: Kindred 
  21: Miss Fortune 
  62: Wukong 
  53: Blitzcrank 
  98: Shen 
  201: Braum 
  5: Xin Zhao 
  29: Twitch 
  11: Master Yi 
  44: Taric 
  32: Amumu 
  41: Gangplank 
  48: Trundle 
  38: Kassadin 
  161: Vel'Koz 
  143: Zyra 
  267: Nami 
  59: Jarvan IV 
  81: Ezreal
  164: Camille 
  498: Xayah 
  497: Rakan 
  141: Kayn 
  516: Ornn 
  142: Zoe 
  145: Kai'Sa 
  555: Pyke 
  518: Neeko 
  517: Sylas 
  350: Yummi 
  246: Qiyana
  235: Senna 
  523: Aphelios <3 
  875: Sett }

